// Generated by CoffeeScript 1.3.3
var app, express, pkg, program;

express = require('express');

program = require('commander');

pkg = require('../package');

app = module.exports = express.createServer();

program.version(pkg.version).option('-p, --port <port>', 'REST service port', 3000).option('-b, --mongo <string>', 'MongoDB connection string', 'mongo://localhost/default').option('-m, --memcached <string>', 'Memcached servers list', '127.0.0.1:11211').option('--memcached-prefix <string>', 'Memcached keys prefix', 's_').parse(process.argv);

app.configure(function() {
  app.use(express.bodyParser());
  app.use(express.methodOverride());
  app.use(require('./uid'));
  app.use(app.router);
  app.set('memcached', program.memcached);
  app.set('mongobase', program.mongo);
  return app.set('memcachedPrefix', program.memcachedPrefix);
});

app.configure('development', function() {
  return app.use(express.errorHandler({
    dumpExceptions: true,
    showStack: true
  }));
});

app.configure('production', function() {
  return app.use(express.errorHandler());
});

require('./api');

app.listen(program.port, function() {
  return console.log("REST server listening\nPort			: \u001b[91m" + (app.address().port) + "\u001b[0m\nMemcached		: \u001b[91m" + app.settings.memcached + "\u001b[0m\nMemcached Prefix	: \u001b[91m" + app.settings.memcachedPrefix + "\u001b[0m\nMongoDB			: \u001b[91m" + app.settings.mongobase + "\u001b[0m\nMode			: \u001b[91m" + app.settings.env + "\u001b[0m");
});
