// Generated by CoffeeScript 1.3.3
var app, express;

express = require('express');

app = module.exports = express.createServer();

app.configure(function() {
  app.use(express.bodyParser());
  app.use(express.methodOverride());
  app.use(express.cookieParser());
  app.use(require('./uid'));
  return app.use(app.router);
});

app.configure('development', function() {
  app.use(express.errorHandler({
    dumpExceptions: true,
    showStack: true
  }));
  app.set('memcached', '127.0.0.1:11211');
  return app.set('mongobase', 'mongo://localhost/default');
});

app.configure('production', function() {
  app.use(express.errorHandler());
  app.set('memcached', process.env.MEMCACHED);
  return app.set('mongobase', process.env.MONGODB);
});

require('./api');

app.listen(3000, function() {
  return console.log("Express server listening on port " + (app.address().port) + " in " + app.settings.env + " mode");
});
