// Generated by CoffeeScript 1.3.3
var app, express;

express = require('express');

app = module.exports = express.createServer();

app.configure(function() {
  app.use(express.bodyParser());
  app.use(express.methodOverride());
  app.use(app.router);
  return app.set('memcached', ['127.0.0.1:11211']);
});

app.configure('development', function() {
  return app.use(express.errorHandler({
    dumpExceptions: true,
    showStack: true
  }));
});

app.configure('production', function() {
  return app.use(express.errorHandler());
});

require('./api');

app.listen(3000, function() {
  return console.log("Express server listening on port " + (app.address().port) + " in " + app.settings.env + " mode");
});
