// Generated by CoffeeScript 1.3.3
var crypto;

crypto = require('crypto');

module.exports = function(text) {
  var shasum;
  shasum = crypto.createHash('md5');
  shasum.update(text);
  return shasum.digest('hex');
};
