// Generated by CoffeeScript 1.3.3
var app;

app = require('./app');

module.exports = function(req, res, next) {
  var uid;
  uid = req.query.uid;
  if (uid != null) {
    req.uid = uid;
    return next();
  } else {
    return res.send(403);
  }
};
