// Generated by CoffeeScript 1.3.3
var crypto, md5;

crypto = require('crypto');

md5 = function(text) {
  var shasum;
  shasum = crypto.createHash('md5');
  shasum.update(text);
  return shasum.digest('hex');
};

module.exports = function(req, res, next) {
  var uid;
  uid = req.cookies.cntuid;
  if (uid != null) {
    req.uid = md5(uid);
    return next();
  } else {
    return res.send(403);
  }
};
