// Generated by CoffeeScript 1.3.3

module.exports = function(req, res, next) {
  var uid;
  uid = req.cookies.cntuid;
  if (uid != null) {
    req.uid = uid;
    return next();
  } else {
    return res.send(403);
  }
};
