// Generated by CoffeeScript 1.3.3
var app, memcached;

memcached = require('./memcached');

app = require('./app');

module.exports = function(uid, version, callback) {
  var key;
  key = "" + app.settings.memcachedPrefix + uid;
  return memcached.set(key, 0, version, function(err, result) {
    return memcached.gets(key, function(err, result) {
      if (err) {
        return callback(503);
      } else {
        return memcached.cas(key, 0, result.cas, version, function(err, result) {
          if (err) {
            return callback(503);
          } else {
            return callback(200);
          }
        });
      }
    });
  });
};
