// Generated by CoffeeScript 1.3.3
var memcached;

memcached = require('./memcached');

module.exports = function(uid, version, callback) {
  return memcached.set(uid, 0, version, function(err, result) {
    return memcached.gets(uid, function(err, result) {
      if (err) {
        return callback(503);
      } else {
        return memcached.cas(uid, 0, result.cas, version, function(err, result) {
          if (err) {
            return callback(503);
          } else {
            return callback(200);
          }
        });
      }
    });
  });
};
